- README.md
> IWTR-32 #comment close

- posts/admin.py
- posts/models.py
posts앱 model 생성
Gallery, Artist, Exhibition, Review 클래스 추가
admin site 모델 등록
- Close #IWTR-42
> IWTR-42 #comment feat : 모델 구현

- templates/navbar.html
- navbar(상단바) 추가
- navbar 생성 완료 
- bootstrap , googlefont 링크 추가
- 로고 생성
- 로그인 회원가입 버튼 생성\
- static 연동 추후 확인
> IWTR-46 #comment feat : create navbar baseline

- templates/footer.html
- footer(하단바) 추가
footer 기본 틀 작성 
- 이미지 추가
- 팀 개인 깃허브 링크 연동
> IWTR-43 #comment feat : create footer baseline

- accounts/templates/accounts/login.html
- templates/navbar.html
login 템플릿 구현
login 템플릿 생성
navbar login url 연결
navbar logo 이미지와 navbar 중앙 "NOW" 텍스트에 index url 연결
- Close #IWTR-44
> IWTR-44 #comment feat : create login.html

- posts/templates/posts/theme2.html
- posts/urls.py
- posts/views.py
- static/css/style.css
- posts/theme2 로 임시 작성
- style.css 추가
- post_list 를 theme2 로 임시 생성
- urls,views 에 theme2 임시 생성(추후 삭제 or 수정 )
- style.css 추가
위와 동일.
x
> IWTR-82 #comment feat : 전시회 리스트 기본 틀 작성

- accounts/forms.py
- accounts/templates/accounts/signup.html
- templates/navbar.html
회원가입 페이지 완성
- navbar url 연결
- Update accounts/signup.html : 회원가입 화면 구현
- Update accounts/forms.py : LogInForm 생성 LogInForm, CustomUserCreationForm 위젯 설정
- 로그인 페이지 modal 형식 2차 개발로 보류
- Close #IWTR-59
> IWTR-59 #comment feat : 회원가입 기능 추가

- accounts/forms.py
accounts/forms.py 내용 수정
accounts/forms.py 내용 수정
- 내용을 적어주세요.
- Close #이슈번호
> forms.py 수정

- accounts/urls.py
- templates/navbar.html
profile 페이지 접속 오류 수정
- Update accounts/url.py 중복 제거
- Update base/navber.html profile 페이지 url 수정
없음
- Close #IWTR-45
> IWTR-45 #comment feat : base 템플릿 추가 수정

- posts/templates/posts/review_create.html
- posts/templates/posts/review_update.html
- posts/urls.py
- posts/views.py
-리뷰 기능 추가
- review_create.html 추가
- review_update.html 추가
- posts/views.py 수정
- posts/urls.py 수정
> IWTR-73 #comment feat : 리뷰 기능 추가

- templates/base.html
- templates/navbar.html
- navbar 프로필 버튼 및 로그아웃 버튼 수정
- Update templates/navbar.html : 로그인 화면 프로필 버튼 드롭다운 구현
- Update logout : 로그아웃 버튼 드롭다운 목록에 적용
- Update templates/base.html : head 태그에 link 블럭 생성
> IWTR-89 #comment feat : navbar 프로필 드롭다운 구현

- posts/templates/posts/post_list.html
post_list.html 에 반복문 추가
Add iteration in post_list.html
> IWTR-23 #comment fix : post-list 템플릿

- posts/templates/posts/detail.html
- posts/urls.py
- posts/views.py
-posts 좋아요 기능 추가
-posts/urls.py 수정
-posts/views.py 수정
> IWTR-101 #comment feat : posts에 좋아요 기능 추가

- accounts/templates/accounts/profile.html
- error : profile.html review 로직
- 프로필 페이지 리뷰 로직 오류 수정
> IWTR-75 #comment feat : 프로필 오류 수정

- posts/forms.py
- posts/templates/posts/detail.html
- posts/templates/posts/index.html
- posts/templates/posts/post_list.html
- posts/templates/posts/review.html
- static/css/style.css
- update posts 
- post_list 재설정 
- 설명에 mt값 추가해야 함! 
- review 틀 작성 , 삭제버튼 , 좋아요 버튼 , 수정하기 버튼 
- 좋아요 개수 나타낼지 안나타낼지 의논  
- index 애니메이션 추가 , description 앞 화살표 이미지 추가
> IWTR-66 IWTR-69 #comment feat:post_list 수정 #comment feat:review,index 수정

- accounts/templates/accounts/profile.html
- profile 사용자의 게시물 정보 출력 연결
- Update profile.html
: 좋아요한 게시물
: 리뷰남긴 게시물
: 팔로우 목록
> IWTR-104 #comment feat : profile 사용자의 게시물 정보 출력 연결

- posts/templates/posts/detail.html
- posts/templates/posts/review.html
- static/css/style.css
-posts css 수정
-posts css 수정
- [ x] 브랜치 확인 부탁드립니다.
> ITWR-?? #comment feat : update posts

- posts/templates/posts/post_list.html
- templates/base.html
> ITWR-?? #comment feat : post_list

- posts/models.py
- posts/templates/posts/detail.html
- posts/views.py
좋아요 버튼 비동기 적용
- Add async script
> IWTR-?? #comment feat : 좋아요 async

- accounts/models.py
- posts/templates/posts/detail.html
- posts/templates/posts/review.html
- posts/urls.py
- posts/views.py
- requirements.txt
- detail 페이지 게시글과 리뷰에 대한 좋아요 기능 비동기 구현
- Update posts
: detail.html/ review.html/ urls.py/ views.py
- Update accounts: models.py
- Update requirements.txt
> IWTR-105 #comment feat : review 좋아요 비동기 구현
